sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank3387/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shashank3387/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-415362078884'
  bucket_path: 'docker-react'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master

